"""MSP 1.0.3 §52: canary rollout of detection rules

Revision ID: 5ea31148fc97
Revises: 93465d97c398
Create Date: 2026-10-01 13:51:08.361236
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - used by rendered JSONB variants
from sqlalchemy.dialects import postgresql

revision: str = "5ea31148fc97"
down_revision: str | None = "93465d97c398"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rule_canaries",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("rule_id", sa.String(length=32), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column(
            "scope",
            sa.Enum("MAILBOX", "DEPARTMENT", "PERCENT", name="canary_scope_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("scope_values", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("percent", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("ACTIVE", "PROMOTED", "ABORTED", name="canary_state_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("review_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=320), nullable=False),
        sa.Column("decided_by", sa.String(length=320), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_rule_canaries_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_canaries")),
    )
    op.create_index("ix_canary_org_rule", "rule_canaries", ["organization_id", "rule_id"], unique=False)
    op.create_index("ix_canary_state", "rule_canaries", ["organization_id", "state"], unique=False)
    op.create_index(op.f("ix_rule_canaries_created_at"), "rule_canaries", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_rule_canaries_organization_id"), "rule_canaries", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_rule_canaries_review_at"), "rule_canaries", ["review_at"], unique=False)
    op.create_index(op.f("ix_rule_canaries_rule_id"), "rule_canaries", ["rule_id"], unique=False)
    op.create_index(op.f("ix_rule_canaries_state"), "rule_canaries", ["state"], unique=False)
    op.add_column("detection_signals", sa.Column("withheld_by", sa.String(length=16), nullable=True))
    op.create_index(
        op.f("ix_detection_signals_withheld_by"), "detection_signals", ["withheld_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_detection_signals_withheld_by"), table_name="detection_signals")
    op.drop_column("detection_signals", "withheld_by")
    op.drop_index(op.f("ix_rule_canaries_state"), table_name="rule_canaries")
    op.drop_index(op.f("ix_rule_canaries_rule_id"), table_name="rule_canaries")
    op.drop_index(op.f("ix_rule_canaries_review_at"), table_name="rule_canaries")
    op.drop_index(op.f("ix_rule_canaries_organization_id"), table_name="rule_canaries")
    op.drop_index(op.f("ix_rule_canaries_created_at"), table_name="rule_canaries")
    op.drop_index("ix_canary_state", table_name="rule_canaries")
    op.drop_index("ix_canary_org_rule", table_name="rule_canaries")
    op.drop_table("rule_canaries")
    # ### end Alembic commands ###
