"""MSP 1.0.4 gap reason rule noise review

Revision ID: 73468c34602f
Revises: c9d0724fbcbb
Create Date: 2026-10-09 14:35:12.207476
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - used by rendered JSONB variants

revision: str = "73468c34602f"
down_revision: str | None = "c9d0724fbcbb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "real_flow_rule_reviews",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("rule_id", sa.String(length=32), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "PRODUCTION_NOISY",
                "ACCEPTABLE",
                "NEEDS_RULE_CHANGE",
                name="rule_noise_verdict_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=320), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=2000), nullable=False),
        sa.Column("triggers_per_1000", sa.Float(), nullable=True),
        sa.Column("fp_per_1000", sa.Float(), nullable=True),
        sa.Column("distinct_messages", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_real_flow_rule_reviews_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_real_flow_rule_reviews")),
        sa.UniqueConstraint("organization_id", "rule_id", name="uq_real_flow_rule_review"),
    )
    op.create_index(
        "ix_real_flow_rule_review_org", "real_flow_rule_reviews", ["organization_id", "verdict"], unique=False
    )
    # detection_gaps уже наполнена: NOT NULL без значения по умолчанию не прошёл бы на
    # существующих строках. Значение ставится при добавлении и тут же снимается — в модели его
    # нет, и оставленный server_default начал бы расходиться с ней.
    op.add_column(
        "detection_gaps",
        sa.Column("validation_reason", sa.Text(), nullable=False, server_default=""),
    )
    op.alter_column("detection_gaps", "validation_reason", server_default=None)
    # validation_messages создана в c9d0724fbcbb и в рабочих установках пуста, но значение по
    # умолчанию ставится по той же причине: предполагать пустоту таблицы — не то же, что знать её.
    op.add_column(
        "validation_messages",
        sa.Column("gap_id", sa.String(length=32), nullable=False, server_default=""),
    )
    op.alter_column("validation_messages", "gap_id", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("validation_messages", "gap_id")
    op.drop_column("detection_gaps", "validation_reason")
    op.drop_index("ix_real_flow_rule_review_org", table_name="real_flow_rule_reviews")
    op.drop_table("real_flow_rule_reviews")
    # ### end Alembic commands ###
