"""MSP 1.0.3: rule lifecycle, analyst workflow, detection quality

Revision ID: 93465d97c398
Revises: 9201086b7406
Create Date: 2026-10-01 03:47:24.890564
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - used by rendered JSONB variants
from sqlalchemy.dialects import postgresql

revision: str = "93465d97c398"
down_revision: str | None = "9201086b7406"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detection_gaps",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("gap_id", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("root_cause", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("info", "low", "medium", "high", "critical", name="severity_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "ACCEPTED",
                "IN_PROGRESS",
                "FIXED",
                "WONT_FIX",
                name="gap_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("owner", sa.String(length=320), nullable=False),
        sa.Column("target_release", sa.String(length=32), nullable=False),
        sa.Column("examples", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("mitigation", sa.Text(), nullable=False),
        sa.Column("planned_fix", sa.Text(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_detection_gaps_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection_gaps")),
        sa.UniqueConstraint("organization_id", "gap_id", name="uq_detection_gap"),
    )
    op.create_index(op.f("ix_detection_gaps_category"), "detection_gaps", ["category"], unique=False)
    op.create_index(op.f("ix_detection_gaps_created_at"), "detection_gaps", ["created_at"], unique=False)
    op.create_index(op.f("ix_detection_gaps_gap_id"), "detection_gaps", ["gap_id"], unique=False)
    op.create_index(
        op.f("ix_detection_gaps_organization_id"), "detection_gaps", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_detection_gaps_severity"), "detection_gaps", ["severity"], unique=False)
    op.create_index(op.f("ix_detection_gaps_status"), "detection_gaps", ["status"], unique=False)
    op.create_table(
        "detection_releases",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("ruleset_fingerprint", sa.Text(), nullable=False),
        sa.Column("dataset_version", sa.String(length=32), nullable=False),
        sa.Column("dataset_checksum", sa.String(length=64), nullable=False),
        sa.Column("new_rules", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("changed_rules", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("removed_rules", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("metrics", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("gate_result", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column(
            "known_limitations", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("changelog", sa.Text(), nullable=False),
        sa.Column("published_by", sa.String(length=320), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_detection_releases_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection_releases")),
        sa.UniqueConstraint("organization_id", "version", name="uq_detection_release"),
    )
    op.create_index(
        op.f("ix_detection_releases_organization_id"), "detection_releases", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_detection_releases_published_at"), "detection_releases", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_detection_releases_version"), "detection_releases", ["version"], unique=False)
    op.create_table(
        "reevaluation_runs",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("ruleset_fingerprint", sa.Text(), nullable=False),
        sa.Column("messages_examined", sa.Integer(), nullable=False),
        sa.Column("verdict_changed", sa.Integer(), nullable=False),
        sa.Column("newly_suspicious", sa.Integer(), nullable=False),
        sa.Column("newly_cleared", sa.Integer(), nullable=False),
        sa.Column(
            "affected_campaigns", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("affected_users", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("sample", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("requested_by", sa.String(length=320), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reevaluation_runs_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reevaluation_runs")),
    )
    op.create_index(
        op.f("ix_reevaluation_runs_organization_id"), "reevaluation_runs", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_reevaluation_runs_started_at"), "reevaluation_runs", ["started_at"], unique=False
    )
    op.create_table(
        "rule_changes",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("rule_id", sa.String(length=32), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=False),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("author", sa.String(length=320), nullable=False),
        sa.Column("reviewer", sa.String(length=320), nullable=False),
        sa.Column("change_reason", sa.String(length=1000), nullable=False),
        sa.Column("before_metrics", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("after_metrics", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_rule_changes_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_changes")),
    )
    op.create_index(op.f("ix_rule_changes_created_at"), "rule_changes", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_rule_changes_organization_id"), "rule_changes", ["organization_id"], unique=False
    )
    op.create_index("ix_rule_changes_rule", "rule_changes", ["rule_id", "created_at"], unique=False)
    op.create_index(op.f("ix_rule_changes_rule_id"), "rule_changes", ["rule_id"], unique=False)
    op.create_table(
        "rule_registry",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("rule_id", sa.String(length=32), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("owner", sa.String(length=320), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("scenarios", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("last_status_change", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_false_positive_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_rule_registry_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_registry")),
        sa.UniqueConstraint("organization_id", "rule_id", name="uq_rule_registry"),
    )
    op.create_index(op.f("ix_rule_registry_created_at"), "rule_registry", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_rule_registry_organization_id"), "rule_registry", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_rule_registry_rule_id"), "rule_registry", ["rule_id"], unique=False)
    op.create_index(op.f("ix_rule_registry_status"), "rule_registry", ["status"], unique=False)
    op.create_table(
        "threat_scenarios",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("scenario_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("rules", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("fixtures", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("playbook", sa.String(length=64), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("info", "low", "medium", "high", "critical", name="severity_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_threat_scenarios_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_threat_scenarios")),
        sa.UniqueConstraint("organization_id", "scenario_id", name="uq_threat_scenario"),
    )
    op.create_index(op.f("ix_threat_scenarios_category"), "threat_scenarios", ["category"], unique=False)
    op.create_index(op.f("ix_threat_scenarios_created_at"), "threat_scenarios", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_threat_scenarios_organization_id"), "threat_scenarios", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_threat_scenarios_scenario_id"), "threat_scenarios", ["scenario_id"], unique=False
    )
    op.create_table(
        "analysis_revisions",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("analysis_job_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("original_classification", sa.String(length=16), nullable=False),
        sa.Column("new_classification", sa.String(length=16), nullable=False),
        sa.Column("original_score", sa.Integer(), nullable=False),
        sa.Column("new_score", sa.Integer(), nullable=False),
        sa.Column("added_rules", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("removed_rules", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("versions", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("requested_by", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_analysis_revisions_analysis_job_id_analysis_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_analysis_revisions_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_analysis_revisions_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_revisions")),
    )
    op.create_index(
        op.f("ix_analysis_revisions_analysis_job_id"), "analysis_revisions", ["analysis_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_revisions_created_at"), "analysis_revisions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_revisions_message_id"), "analysis_revisions", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_revisions_organization_id"), "analysis_revisions", ["organization_id"], unique=False
    )
    op.create_index("ix_revision_job", "analysis_revisions", ["analysis_job_id", "created_at"], unique=False)
    op.create_table(
        "detection_feedback",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column("incident_id", sa.String(length=32), nullable=True),
        sa.Column("rule_id", sa.String(length=32), nullable=True),
        sa.Column("analyst_email", sa.String(length=320), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("root_cause", sa.String(length=32), nullable=False),
        sa.Column("expected_detection", sa.String(length=255), nullable=False),
        sa.Column("missing_fact", sa.String(length=255), nullable=False),
        sa.Column("gap_id", sa.String(length=32), nullable=True),
        sa.Column("proposed_exception_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_detection_feedback_incident_id_incidents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_detection_feedback_message_id_mail_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_detection_feedback_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection_feedback")),
    )
    op.create_index(
        op.f("ix_detection_feedback_created_at"), "detection_feedback", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_detection_feedback_gap_id"), "detection_feedback", ["gap_id"], unique=False)
    op.create_index(
        op.f("ix_detection_feedback_incident_id"), "detection_feedback", ["incident_id"], unique=False
    )
    op.create_index(op.f("ix_detection_feedback_kind"), "detection_feedback", ["kind"], unique=False)
    op.create_index(
        op.f("ix_detection_feedback_message_id"), "detection_feedback", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_detection_feedback_organization_id"), "detection_feedback", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_detection_feedback_rule_id"), "detection_feedback", ["rule_id"], unique=False)
    op.create_index("ix_feedback_rule", "detection_feedback", ["rule_id", "created_at"], unique=False)
    op.create_table(
        "incident_assignments",
        sa.Column("incident_id", sa.String(length=32), nullable=False),
        sa.Column("assignee_id", sa.String(length=32), nullable=True),
        sa.Column("assignee_email", sa.String(length=320), nullable=False),
        sa.Column("assigned_by", sa.String(length=320), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"], ["users.id"], name=op.f("fk_incident_assignments_assignee_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_assignments_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_assignments")),
    )
    op.create_index(
        op.f("ix_incident_assignments_assigned_at"), "incident_assignments", ["assigned_at"], unique=False
    )
    op.create_index(
        op.f("ix_incident_assignments_assignee_id"), "incident_assignments", ["assignee_id"], unique=False
    )
    op.create_index(
        op.f("ix_incident_assignments_incident_id"), "incident_assignments", ["incident_id"], unique=False
    )
    op.create_table(
        "incident_classifications",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("incident_id", sa.String(length=32), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "CONFIRMED_PHISHING",
                "CONFIRMED_BEC",
                "CONFIRMED_MALWARE",
                "SPAM",
                "LEGITIMATE",
                "FALSE_POSITIVE",
                "BENIGN_SIMULATION",
                "UNKNOWN",
                name="analyst_classification_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("previous_classification", sa.String(length=32), nullable=True),
        sa.Column("analyst_id", sa.String(length=32), nullable=True),
        sa.Column("analyst_email", sa.String(length=320), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "offending_signals", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "offending_rules", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["analyst_id"], ["users.id"], name=op.f("fk_incident_classifications_analyst_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_classifications_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_incident_classifications_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_classifications")),
    )
    op.create_index(
        "ix_classification_incident", "incident_classifications", ["incident_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_incident_classifications_classification"),
        "incident_classifications",
        ["classification"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_classifications_created_at"),
        "incident_classifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_classifications_incident_id"),
        "incident_classifications",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_classifications_organization_id"),
        "incident_classifications",
        ["organization_id"],
        unique=False,
    )
    # Existing deployments already hold rows in these tables, so a NOT NULL column needs a
    # value for them. The server default fills the backlog and is then dropped: the default
    # belongs in the model, and leaving it in the schema would let an INSERT that forgot the
    # column succeed silently.
    op.add_column(
        "detection_exceptions",
        sa.Column(
            "scope",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'RULE'"),
        ),
    )
    op.alter_column("detection_exceptions", "scope", server_default=None)
    op.add_column(
        "detection_exceptions",
        sa.Column(
            "created_by",
            sa.String(length=320),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_exceptions", "created_by", server_default=None)
    op.add_column("detection_exceptions", sa.Column("approved_by", sa.String(length=320), nullable=True))
    op.add_column("detection_exceptions", sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "detection_exceptions",
        sa.Column(
            "requires_approval",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.alter_column("detection_exceptions", "requires_approval", server_default=None)
    op.add_column("detection_exceptions", sa.Column("review_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("detection_exceptions", sa.Column("last_hit_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        op.f("ix_detection_exceptions_review_at"), "detection_exceptions", ["review_at"], unique=False
    )
    op.create_index(op.f("ix_detection_exceptions_scope"), "detection_exceptions", ["scope"], unique=False)
    op.add_column(
        "detection_signals",
        sa.Column("shadow", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.alter_column("detection_signals", "shadow", server_default=None)
    op.add_column(
        "detection_signals",
        sa.Column("rule_status", sa.String(length=16), nullable=False, server_default=sa.text("'ACTIVE'")),
    )
    op.alter_column("detection_signals", "rule_status", server_default=None)
    op.create_index(op.f("ix_detection_signals_shadow"), "detection_signals", ["shadow"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_detection_signals_shadow"), table_name="detection_signals")
    op.drop_column("detection_signals", "rule_status")
    op.drop_column("detection_signals", "shadow")
    op.drop_index(op.f("ix_detection_exceptions_scope"), table_name="detection_exceptions")
    op.drop_index(op.f("ix_detection_exceptions_review_at"), table_name="detection_exceptions")
    op.drop_column("detection_exceptions", "last_hit_at")
    op.drop_column("detection_exceptions", "review_at")
    op.drop_column("detection_exceptions", "requires_approval")
    op.drop_column("detection_exceptions", "approved_at")
    op.drop_column("detection_exceptions", "approved_by")
    op.drop_column("detection_exceptions", "created_by")
    op.drop_column("detection_exceptions", "scope")
    op.drop_index(op.f("ix_incident_classifications_organization_id"), table_name="incident_classifications")
    op.drop_index(op.f("ix_incident_classifications_incident_id"), table_name="incident_classifications")
    op.drop_index(op.f("ix_incident_classifications_created_at"), table_name="incident_classifications")
    op.drop_index(op.f("ix_incident_classifications_classification"), table_name="incident_classifications")
    op.drop_index("ix_classification_incident", table_name="incident_classifications")
    op.drop_table("incident_classifications")
    op.drop_index(op.f("ix_incident_assignments_incident_id"), table_name="incident_assignments")
    op.drop_index(op.f("ix_incident_assignments_assignee_id"), table_name="incident_assignments")
    op.drop_index(op.f("ix_incident_assignments_assigned_at"), table_name="incident_assignments")
    op.drop_table("incident_assignments")
    op.drop_index("ix_feedback_rule", table_name="detection_feedback")
    op.drop_index(op.f("ix_detection_feedback_rule_id"), table_name="detection_feedback")
    op.drop_index(op.f("ix_detection_feedback_organization_id"), table_name="detection_feedback")
    op.drop_index(op.f("ix_detection_feedback_message_id"), table_name="detection_feedback")
    op.drop_index(op.f("ix_detection_feedback_kind"), table_name="detection_feedback")
    op.drop_index(op.f("ix_detection_feedback_incident_id"), table_name="detection_feedback")
    op.drop_index(op.f("ix_detection_feedback_gap_id"), table_name="detection_feedback")
    op.drop_index(op.f("ix_detection_feedback_created_at"), table_name="detection_feedback")
    op.drop_table("detection_feedback")
    op.drop_index("ix_revision_job", table_name="analysis_revisions")
    op.drop_index(op.f("ix_analysis_revisions_organization_id"), table_name="analysis_revisions")
    op.drop_index(op.f("ix_analysis_revisions_message_id"), table_name="analysis_revisions")
    op.drop_index(op.f("ix_analysis_revisions_created_at"), table_name="analysis_revisions")
    op.drop_index(op.f("ix_analysis_revisions_analysis_job_id"), table_name="analysis_revisions")
    op.drop_table("analysis_revisions")
    op.drop_index(op.f("ix_threat_scenarios_scenario_id"), table_name="threat_scenarios")
    op.drop_index(op.f("ix_threat_scenarios_organization_id"), table_name="threat_scenarios")
    op.drop_index(op.f("ix_threat_scenarios_created_at"), table_name="threat_scenarios")
    op.drop_index(op.f("ix_threat_scenarios_category"), table_name="threat_scenarios")
    op.drop_table("threat_scenarios")
    op.drop_index(op.f("ix_rule_registry_status"), table_name="rule_registry")
    op.drop_index(op.f("ix_rule_registry_rule_id"), table_name="rule_registry")
    op.drop_index(op.f("ix_rule_registry_organization_id"), table_name="rule_registry")
    op.drop_index(op.f("ix_rule_registry_created_at"), table_name="rule_registry")
    op.drop_table("rule_registry")
    op.drop_index(op.f("ix_rule_changes_rule_id"), table_name="rule_changes")
    op.drop_index("ix_rule_changes_rule", table_name="rule_changes")
    op.drop_index(op.f("ix_rule_changes_organization_id"), table_name="rule_changes")
    op.drop_index(op.f("ix_rule_changes_created_at"), table_name="rule_changes")
    op.drop_table("rule_changes")
    op.drop_index(op.f("ix_reevaluation_runs_started_at"), table_name="reevaluation_runs")
    op.drop_index(op.f("ix_reevaluation_runs_organization_id"), table_name="reevaluation_runs")
    op.drop_table("reevaluation_runs")
    op.drop_index(op.f("ix_detection_releases_version"), table_name="detection_releases")
    op.drop_index(op.f("ix_detection_releases_published_at"), table_name="detection_releases")
    op.drop_index(op.f("ix_detection_releases_organization_id"), table_name="detection_releases")
    op.drop_table("detection_releases")
    op.drop_index(op.f("ix_detection_gaps_status"), table_name="detection_gaps")
    op.drop_index(op.f("ix_detection_gaps_severity"), table_name="detection_gaps")
    op.drop_index(op.f("ix_detection_gaps_organization_id"), table_name="detection_gaps")
    op.drop_index(op.f("ix_detection_gaps_gap_id"), table_name="detection_gaps")
    op.drop_index(op.f("ix_detection_gaps_created_at"), table_name="detection_gaps")
    op.drop_index(op.f("ix_detection_gaps_category"), table_name="detection_gaps")
    op.drop_table("detection_gaps")
    # ### end Alembic commands ###
