"""MSP 1.0.3B: feedback domain, candidates, releases, campaign matches, reanalysis

Revision ID: 8eb92e7ae88f
Revises: 5ea31148fc97
Create Date: 2026-10-01 23:06:13.400329
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - used by rendered JSONB variants
from sqlalchemy.dialects import postgresql

revision: str = "8eb92e7ae88f"
down_revision: str | None = "5ea31148fc97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Existing deployments already hold rows in these tables, so a NOT NULL column needs a
    # value for them. The server default fills the backlog and is dropped immediately after:
    # the default belongs in the model, and leaving it in the schema would let an INSERT that
    # forgot the column succeed silently.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reanalysis_jobs",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "PAUSED",
                "CANCELLED",
                "COMPLETED",
                "FAILED",
                name="reanalysis_state_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("window_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("filters", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("ruleset_source", sa.String(length=512), nullable=False),
        sa.Column("ruleset_fingerprint", sa.Text(), nullable=False),
        sa.Column("max_messages", sa.Integer(), nullable=False),
        sa.Column("total_messages", sa.Integer(), nullable=False),
        sa.Column("processed", sa.Integer(), nullable=False),
        sa.Column("verdict_changed", sa.Integer(), nullable=False),
        sa.Column("newly_suspicious", sa.Integer(), nullable=False),
        sa.Column("newly_cleared", sa.Integer(), nullable=False),
        sa.Column("cursor", sa.Integer(), nullable=False),
        sa.Column("sample", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("requested_by", sa.String(length=320), nullable=False),
        sa.Column("cancelled_by", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reanalysis_jobs_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reanalysis_jobs")),
    )
    op.create_index(op.f("ix_reanalysis_jobs_created_at"), "reanalysis_jobs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_reanalysis_jobs_organization_id"), "reanalysis_jobs", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_reanalysis_jobs_state"), "reanalysis_jobs", ["state"], unique=False)
    op.create_index("ix_reanalysis_org_state", "reanalysis_jobs", ["organization_id", "state"], unique=False)
    op.create_table(
        "rule_quality_snapshots",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("rule_id", sa.String(length=32), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("ruleset_version", sa.String(length=64), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trigger_count", sa.Integer(), nullable=False),
        sa.Column("analyst_reviewed", sa.Integer(), nullable=False),
        sa.Column("true_positive", sa.Integer(), nullable=False),
        sa.Column("false_positive", sa.Integer(), nullable=False),
        sa.Column("unknown", sa.Integer(), nullable=False),
        sa.Column("suppressed", sa.Integer(), nullable=False),
        sa.Column("precision", sa.Float(), nullable=True),
        sa.Column("affected_messages", sa.Integer(), nullable=False),
        sa.Column("affected_incidents", sa.Integer(), nullable=False),
        sa.Column(
            "health",
            sa.Enum(
                "HEALTHY",
                "NO_DATA",
                "NOISY",
                "REGRESSED",
                "LOW_COVERAGE",
                "DEGRADED",
                name="rule_health_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("health_reasons", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_rule_quality_snapshots_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_quality_snapshots")),
    )
    op.create_index(
        "ix_rule_quality_rule_period",
        "rule_quality_snapshots",
        ["organization_id", "rule_id", "period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rule_quality_snapshots_created_at"), "rule_quality_snapshots", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_rule_quality_snapshots_health"), "rule_quality_snapshots", ["health"], unique=False
    )
    op.create_index(
        op.f("ix_rule_quality_snapshots_organization_id"),
        "rule_quality_snapshots",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rule_quality_snapshots_period_end"), "rule_quality_snapshots", ["period_end"], unique=False
    )
    op.create_index(
        op.f("ix_rule_quality_snapshots_period_start"),
        "rule_quality_snapshots",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rule_quality_snapshots_rule_id"), "rule_quality_snapshots", ["rule_id"], unique=False
    )
    op.create_table(
        "rule_candidates",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("source_kind", sa.String(length=16), nullable=False),
        sa.Column("ruleset_fingerprint", sa.Text(), nullable=False),
        sa.Column("base_fingerprint", sa.Text(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "DRAFT",
                "READY_FOR_REVIEW",
                "CHANGES_REQUESTED",
                "APPROVED",
                "PUBLISHED",
                "REJECTED",
                name="candidate_state_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("added_rules", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("changed_rules", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("removed_rules", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("critical_change", sa.Boolean(), nullable=False),
        sa.Column(
            "critical_reasons", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("author", sa.String(length=320), nullable=False),
        sa.Column("reviewer", sa.String(length=320), nullable=False),
        sa.Column("review_comment", sa.Text(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("benchmark", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("benchmarked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("release_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_rule_candidates_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["detection_releases.id"],
            name=op.f("fk_rule_candidates_release_id_detection_releases"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_candidates")),
        sa.UniqueConstraint("organization_id", "name", name="uq_rule_candidate_name"),
    )
    op.create_index("ix_rule_candidate_state", "rule_candidates", ["organization_id", "state"], unique=False)
    op.create_index(op.f("ix_rule_candidates_created_at"), "rule_candidates", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_rule_candidates_organization_id"), "rule_candidates", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_rule_candidates_state"), "rule_candidates", ["state"], unique=False)
    op.create_table(
        "campaign_matches",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("campaign_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reasons", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("manual", sa.Boolean(), nullable=False),
        sa.Column("rejected", sa.Boolean(), nullable=False),
        sa.Column("decided_by", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_matches_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_campaign_matches_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_campaign_matches_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_matches")),
        sa.UniqueConstraint("campaign_id", "message_id", name="uq_campaign_match"),
    )
    op.create_index("ix_campaign_match_message", "campaign_matches", ["message_id"], unique=False)
    op.create_index(
        op.f("ix_campaign_matches_campaign_id"), "campaign_matches", ["campaign_id"], unique=False
    )
    op.create_index(op.f("ix_campaign_matches_created_at"), "campaign_matches", ["created_at"], unique=False)
    op.create_index(op.f("ix_campaign_matches_manual"), "campaign_matches", ["manual"], unique=False)
    op.create_index(op.f("ix_campaign_matches_message_id"), "campaign_matches", ["message_id"], unique=False)
    op.create_index(
        op.f("ix_campaign_matches_organization_id"), "campaign_matches", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_campaign_matches_rejected"), "campaign_matches", ["rejected"], unique=False)
    op.create_table(
        "signal_feedback",
        sa.Column("feedback_id", sa.String(length=32), nullable=False),
        sa.Column("signal_id", sa.String(length=64), nullable=True),
        sa.Column("rule_id", sa.String(length=32), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column(
            "disposition",
            sa.Enum(
                "CORRECT",
                "INCORRECT",
                "TOO_SEVERE",
                "TOO_WEAK",
                "IRRELEVANT",
                "DUPLICATE",
                name="signal_disposition_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["detection_feedback.id"],
            name=op.f("fk_signal_feedback_feedback_id_detection_feedback"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_feedback")),
    )
    op.create_index(op.f("ix_signal_feedback_created_at"), "signal_feedback", ["created_at"], unique=False)
    op.create_index(op.f("ix_signal_feedback_disposition"), "signal_feedback", ["disposition"], unique=False)
    op.create_index(op.f("ix_signal_feedback_feedback_id"), "signal_feedback", ["feedback_id"], unique=False)
    op.create_index("ix_signal_feedback_rule", "signal_feedback", ["rule_id", "disposition"], unique=False)
    op.create_index(op.f("ix_signal_feedback_rule_id"), "signal_feedback", ["rule_id"], unique=False)
    op.create_index(op.f("ix_signal_feedback_signal_id"), "signal_feedback", ["signal_id"], unique=False)
    op.add_column("detection_feedback", sa.Column("analyst_id", sa.String(length=32), nullable=True))
    op.add_column("detection_feedback", sa.Column("analysis_id", sa.String(length=32), nullable=True))
    op.add_column(
        "detection_feedback",
        sa.Column(
            "classification",
            sa.String(length=32),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_feedback", "classification", server_default=None)
    op.add_column(
        "detection_feedback",
        sa.Column(
            "confidence",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_feedback", "confidence", server_default=None)
    op.add_column("detection_feedback", sa.Column("fp_reason", sa.String(length=32), nullable=True))
    op.add_column(
        "detection_feedback",
        sa.Column(
            "expected_category",
            sa.String(length=64),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_feedback", "expected_category", server_default=None)
    op.add_column(
        "detection_feedback",
        sa.Column(
            "minimum_classification",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_feedback", "minimum_classification", server_default=None)
    op.add_column(
        "detection_feedback",
        sa.Column(
            "severity",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_feedback", "severity", server_default=None)
    op.add_column(
        "detection_feedback",
        sa.Column(
            "owner",
            sa.String(length=320),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_feedback", "owner", server_default=None)
    op.add_column(
        "detection_feedback",
        sa.Column(
            "target_release",
            sa.String(length=32),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_feedback", "target_release", server_default=None)
    op.create_index(
        op.f("ix_detection_feedback_analysis_id"), "detection_feedback", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_detection_feedback_classification"), "detection_feedback", ["classification"], unique=False
    )
    op.create_index(
        op.f("ix_detection_feedback_fp_reason"), "detection_feedback", ["fp_reason"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_detection_feedback_analysis_id_analysis_jobs"),
        "detection_feedback",
        "analysis_jobs",
        ["analysis_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "detection_gaps",
        sa.Column(
            "discovered_from",
            sa.String(length=32),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_gaps", "discovered_from", server_default=None)
    op.add_column(
        "detection_gaps",
        sa.Column(
            "example_analysis_ids",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
    )
    op.alter_column("detection_gaps", "example_analysis_ids", server_default=None)
    op.add_column(
        "detection_gaps",
        sa.Column(
            "compensating_controls",
            sa.Text(),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_gaps", "compensating_controls", server_default=None)
    op.add_column(
        "detection_releases",
        sa.Column(
            "parser_version",
            sa.String(length=32),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_releases", "parser_version", server_default=None)
    op.add_column(
        "detection_releases",
        sa.Column(
            "risk_engine_version",
            sa.String(length=32),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_releases", "risk_engine_version", server_default=None)
    op.add_column(
        "detection_releases",
        sa.Column(
            "commit_sha",
            sa.String(length=64),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_releases", "commit_sha", server_default=None)
    op.add_column("detection_releases", sa.Column("candidate_id", sa.String(length=32), nullable=True))
    op.add_column(
        "detection_releases",
        sa.Column(
            "approved_by",
            sa.String(length=320),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("detection_releases", "approved_by", server_default=None)
    op.add_column(
        "detection_releases",
        sa.Column(
            "metric_deltas",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
    )
    op.alter_column("detection_releases", "metric_deltas", server_default=None)
    op.alter_column(
        "incident_classifications",
        "classification",
        existing_type=sa.VARCHAR(length=18),
        type_=sa.Enum(
            "CONFIRMED_PHISHING",
            "CONFIRMED_BEC",
            "CONFIRMED_MALWARE",
            "CONFIRMED_SPAM",
            "CONFIRMED_IMPERSONATION",
            "LEGITIMATE",
            "FALSE_POSITIVE",
            "BENIGN_SIMULATION",
            "UNKNOWN",
            name="analyst_classification_enum",
            native_enum=False,
        ),
        existing_nullable=False,
    )

    # The stage aligned three vocabularies with the operational terms of ТЗ 1.0.3B. Stored rows
    # carry the old spellings, and an enum value nothing maps to reads as corrupt data later, so
    # the rename is applied to the data rather than left to chance.
    # The stage aligned three vocabularies with the operational terms of ТЗ 1.0.3B. Stored rows
    # carry the old spellings, and an enum value nothing maps to reads as corrupt data later, so
    # the rename is applied to the data rather than left to chance. The statements are written
    # out rather than built from names: a migration is not the place for a query that has to be
    # read twice to see that it is safe.
    op.execute(
        sa.text(
            "UPDATE incident_classifications SET classification = 'CONFIRMED_SPAM' "
            "WHERE classification = 'SPAM'"
        )
    )
    op.execute(
        sa.text("UPDATE detection_feedback SET root_cause = 'RULE_LOGIC' WHERE root_cause = 'RULE_FAILURE'")
    )
    op.execute(
        sa.text(
            "UPDATE detection_feedback SET root_cause = 'RISK_AGGREGATION' "
            "WHERE root_cause = 'RISK_AGGREGATION_FAILURE'"
        )
    )
    op.execute(sa.text("UPDATE detection_gaps SET status = 'RESOLVED' WHERE status = 'FIXED'"))

    # ### end Alembic commands ###


def downgrade() -> None:

    op.execute(
        sa.text(
            "UPDATE incident_classifications SET classification = 'SPAM' "
            "WHERE classification = 'CONFIRMED_SPAM'"
        )
    )
    op.execute(
        sa.text("UPDATE detection_feedback SET root_cause = 'RULE_FAILURE' WHERE root_cause = 'RULE_LOGIC'")
    )
    op.execute(
        sa.text(
            "UPDATE detection_feedback SET root_cause = 'RISK_AGGREGATION_FAILURE' "
            "WHERE root_cause = 'RISK_AGGREGATION'"
        )
    )
    op.execute(sa.text("UPDATE detection_gaps SET status = 'FIXED' WHERE status = 'RESOLVED'"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "incident_classifications",
        "classification",
        existing_type=sa.Enum(
            "CONFIRMED_PHISHING",
            "CONFIRMED_BEC",
            "CONFIRMED_MALWARE",
            "CONFIRMED_SPAM",
            "CONFIRMED_IMPERSONATION",
            "LEGITIMATE",
            "FALSE_POSITIVE",
            "BENIGN_SIMULATION",
            "UNKNOWN",
            name="analyst_classification_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=18),
        existing_nullable=False,
    )
    op.drop_column("detection_releases", "metric_deltas")
    op.drop_column("detection_releases", "approved_by")
    op.drop_column("detection_releases", "candidate_id")
    op.drop_column("detection_releases", "commit_sha")
    op.drop_column("detection_releases", "risk_engine_version")
    op.drop_column("detection_releases", "parser_version")
    op.drop_column("detection_gaps", "compensating_controls")
    op.drop_column("detection_gaps", "example_analysis_ids")
    op.drop_column("detection_gaps", "discovered_from")
    op.drop_constraint(
        op.f("fk_detection_feedback_analysis_id_analysis_jobs"), "detection_feedback", type_="foreignkey"
    )
    op.drop_index(op.f("ix_detection_feedback_fp_reason"), table_name="detection_feedback")
    op.drop_index(op.f("ix_detection_feedback_classification"), table_name="detection_feedback")
    op.drop_index(op.f("ix_detection_feedback_analysis_id"), table_name="detection_feedback")
    op.drop_column("detection_feedback", "target_release")
    op.drop_column("detection_feedback", "owner")
    op.drop_column("detection_feedback", "severity")
    op.drop_column("detection_feedback", "minimum_classification")
    op.drop_column("detection_feedback", "expected_category")
    op.drop_column("detection_feedback", "fp_reason")
    op.drop_column("detection_feedback", "confidence")
    op.drop_column("detection_feedback", "classification")
    op.drop_column("detection_feedback", "analysis_id")
    op.drop_column("detection_feedback", "analyst_id")
    op.drop_index(op.f("ix_signal_feedback_signal_id"), table_name="signal_feedback")
    op.drop_index(op.f("ix_signal_feedback_rule_id"), table_name="signal_feedback")
    op.drop_index("ix_signal_feedback_rule", table_name="signal_feedback")
    op.drop_index(op.f("ix_signal_feedback_feedback_id"), table_name="signal_feedback")
    op.drop_index(op.f("ix_signal_feedback_disposition"), table_name="signal_feedback")
    op.drop_index(op.f("ix_signal_feedback_created_at"), table_name="signal_feedback")
    op.drop_table("signal_feedback")
    op.drop_index(op.f("ix_campaign_matches_rejected"), table_name="campaign_matches")
    op.drop_index(op.f("ix_campaign_matches_organization_id"), table_name="campaign_matches")
    op.drop_index(op.f("ix_campaign_matches_message_id"), table_name="campaign_matches")
    op.drop_index(op.f("ix_campaign_matches_manual"), table_name="campaign_matches")
    op.drop_index(op.f("ix_campaign_matches_created_at"), table_name="campaign_matches")
    op.drop_index(op.f("ix_campaign_matches_campaign_id"), table_name="campaign_matches")
    op.drop_index("ix_campaign_match_message", table_name="campaign_matches")
    op.drop_table("campaign_matches")
    op.drop_index(op.f("ix_rule_candidates_state"), table_name="rule_candidates")
    op.drop_index(op.f("ix_rule_candidates_organization_id"), table_name="rule_candidates")
    op.drop_index(op.f("ix_rule_candidates_created_at"), table_name="rule_candidates")
    op.drop_index("ix_rule_candidate_state", table_name="rule_candidates")
    op.drop_table("rule_candidates")
    op.drop_index(op.f("ix_rule_quality_snapshots_rule_id"), table_name="rule_quality_snapshots")
    op.drop_index(op.f("ix_rule_quality_snapshots_period_start"), table_name="rule_quality_snapshots")
    op.drop_index(op.f("ix_rule_quality_snapshots_period_end"), table_name="rule_quality_snapshots")
    op.drop_index(op.f("ix_rule_quality_snapshots_organization_id"), table_name="rule_quality_snapshots")
    op.drop_index(op.f("ix_rule_quality_snapshots_health"), table_name="rule_quality_snapshots")
    op.drop_index(op.f("ix_rule_quality_snapshots_created_at"), table_name="rule_quality_snapshots")
    op.drop_index("ix_rule_quality_rule_period", table_name="rule_quality_snapshots")
    op.drop_table("rule_quality_snapshots")
    op.drop_index("ix_reanalysis_org_state", table_name="reanalysis_jobs")
    op.drop_index(op.f("ix_reanalysis_jobs_state"), table_name="reanalysis_jobs")
    op.drop_index(op.f("ix_reanalysis_jobs_organization_id"), table_name="reanalysis_jobs")
    op.drop_index(op.f("ix_reanalysis_jobs_created_at"), table_name="reanalysis_jobs")
    op.drop_table("reanalysis_jobs")
    # ### end Alembic commands ###
