"""MSP 1.0.4 real flow validation and gap evidence

Revision ID: c9d0724fbcbb
Revises: d9663819e595
Create Date: 2026-10-08 22:13:11.798043
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - used by rendered JSONB variants
from sqlalchemy.dialects import postgresql

revision: str = "c9d0724fbcbb"
down_revision: str | None = "d9663819e595"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validation_messages",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "SECURITY_MAILBOX",
                "EWS_READONLY",
                "JOURNAL_COPY",
                "GATEWAY_EVIDENCE",
                "ANALYST_UPLOAD",
                name="validation_source_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("message_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("anonymized", sa.Boolean(), nullable=False),
        sa.Column(
            "pii_status",
            sa.Enum("RAW", "ANONYMIZED", "REVIEWED", "REJECTED", name="pii_status_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "anonymization_report", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("raw_object_key", sa.String(length=512), nullable=False),
        sa.Column("anonymized_object_key", sa.String(length=512), nullable=False),
        sa.Column(
            "expected_classification",
            sa.Enum(
                "LOW_RISK",
                "SUSPICIOUS",
                "HIGH_RISK",
                "MALICIOUS",
                "UNKNOWN",
                name="risk_level_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "analyst_classification",
            sa.Enum(
                "CONFIRMED_PHISHING",
                "CONFIRMED_BEC",
                "CONFIRMED_MALWARE",
                "CONFIRMED_SPAM",
                "CONFIRMED_IMPERSONATION",
                "LEGITIMATE",
                "FALSE_POSITIVE",
                "BENIGN_SIMULATION",
                "UNKNOWN",
                name="analyst_classification_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("reviewed_by", sa.String(length=320), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_comment", sa.String(length=2000), nullable=False),
        sa.Column(
            "production_verdict",
            sa.Enum(
                "LOW_RISK",
                "SUSPICIOUS",
                "HIGH_RISK",
                "MALICIOUS",
                "UNKNOWN",
                name="risk_level_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "validation_verdict",
            sa.Enum(
                "LOW_RISK",
                "SUSPICIOUS",
                "HIGH_RISK",
                "MALICIOUS",
                "UNKNOWN",
                name="risk_level_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("ruleset_version", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("risk_engine_version", sa.String(length=64), nullable=False),
        sa.Column(
            "triggered_rules", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "sampling_reasons", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "unscannable_reasons", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "promotion_state",
            sa.Enum(
                "NOT_REQUESTED",
                "REQUESTED",
                "APPROVED",
                "PROMOTED",
                "REJECTED",
                name="promotion_state_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("promotion_requested_by", sa.String(length=320), nullable=False),
        sa.Column("promotion_approved_by", sa.String(length=320), nullable=False),
        sa.Column("promotion_case_id", sa.String(length=32), nullable=False),
        sa.Column("promoted_dataset_version", sa.String(length=32), nullable=False),
        sa.Column(
            "reproducibility_report", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("raw_retained_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_validation_messages_message_id_mail_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_validation_messages_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_messages")),
        sa.UniqueConstraint("organization_id", "message_fingerprint", name="uq_validation_message"),
    )
    op.create_index(
        op.f("ix_validation_messages_message_id"), "validation_messages", ["message_id"], unique=False
    )
    op.create_index(
        "ix_validation_org_pii", "validation_messages", ["organization_id", "pii_status"], unique=False
    )
    op.create_index(
        "ix_validation_org_promotion",
        "validation_messages",
        ["organization_id", "promotion_state"],
        unique=False,
    )
    op.create_index(
        "ix_validation_org_raw_retention",
        "validation_messages",
        ["organization_id", "raw_retained_until"],
        unique=False,
    )
    op.create_index(
        "ix_validation_org_received", "validation_messages", ["organization_id", "received_at"], unique=False
    )
    op.create_index(
        "ix_validation_org_review",
        "validation_messages",
        ["organization_id", "analyst_classification"],
        unique=False,
    )
    op.add_column(
        "detection_gaps", sa.Column("real_flow_validated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # Таблица уже наполнена: NOT NULL без значения по умолчанию не прошёл бы на существующих
    # строках. Значение ставится при добавлении и тут же снимается — в модели его нет, и
    # оставленный server_default начал бы расходиться с ней.
    op.add_column(
        "detection_gaps",
        sa.Column("real_flow_validated_by", sa.String(length=320), nullable=False, server_default=""),
    )
    op.add_column(
        "detection_gaps",
        sa.Column(
            "real_flow_evidence",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    op.alter_column("detection_gaps", "real_flow_validated_by", server_default=None)
    op.alter_column("detection_gaps", "real_flow_evidence", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("detection_gaps", "real_flow_evidence")
    op.drop_column("detection_gaps", "real_flow_validated_by")
    op.drop_column("detection_gaps", "real_flow_validated_at")
    op.drop_index("ix_validation_org_review", table_name="validation_messages")
    op.drop_index("ix_validation_org_received", table_name="validation_messages")
    op.drop_index("ix_validation_org_raw_retention", table_name="validation_messages")
    op.drop_index("ix_validation_org_promotion", table_name="validation_messages")
    op.drop_index("ix_validation_org_pii", table_name="validation_messages")
    op.drop_index(op.f("ix_validation_messages_message_id"), table_name="validation_messages")
    op.drop_table("validation_messages")
    # ### end Alembic commands ###
