"""MSP 1.0.4 protected domain variants

Revision ID: d9663819e595
Revises: 8eb92e7ae88f
Create Date: 2026-10-04 09:56:07.325518
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - used by rendered JSONB variants

revision: str = "d9663819e595"
down_revision: str | None = "8eb92e7ae88f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "protected_domain_variants",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("protected_domain", sa.String(length=253), nullable=False),
        sa.Column("candidate_domain", sa.String(length=253), nullable=False),
        sa.Column("transform_type", sa.String(length=32), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "GENERATED",
                "OBSERVED",
                "APPROVED_SUSPICIOUS",
                "KNOWN_LEGITIMATE",
                "IGNORED",
                name="domain_variant_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_count", sa.Integer(), nullable=False),
        sa.Column("decided_by", sa.String(length=320), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_protected_domain_variants_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_protected_domain_variants")),
        sa.UniqueConstraint(
            "organization_id", "protected_domain", "candidate_domain", name="uq_domain_variant"
        ),
    )
    op.create_index(
        "ix_domain_variant_candidate",
        "protected_domain_variants",
        ["organization_id", "candidate_domain"],
        unique=False,
    )
    op.create_index(
        "ix_domain_variant_status", "protected_domain_variants", ["organization_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_protected_domain_variants_generated_at"),
        "protected_domain_variants",
        ["generated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_protected_domain_variants_organization_id"),
        "protected_domain_variants",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_protected_domain_variants_organization_id"), table_name="protected_domain_variants"
    )
    op.drop_index(op.f("ix_protected_domain_variants_generated_at"), table_name="protected_domain_variants")
    op.drop_index("ix_domain_variant_status", table_name="protected_domain_variants")
    op.drop_index("ix_domain_variant_candidate", table_name="protected_domain_variants")
    op.drop_table("protected_domain_variants")
    # ### end Alembic commands ###
