"""MSP 1.0.1 and 1.0.2: durable intake, trusted hops, gateway evidence

Revision ID: 9201086b7406
Revises: 043db9650df6
Create Date: 2026-09-29 23:37:14.121570
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - used by rendered JSONB variants
from sqlalchemy.dialects import postgresql

revision: str = "9201086b7406"
down_revision: str | None = "043db9650df6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "syslog_dead_letters",
        sa.Column("organization_id", sa.String(length=32), nullable=True),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("source_ip", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.String(length=500), nullable=False),
        sa.Column("raw", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_syslog_dead_letters")),
    )
    op.create_index(
        op.f("ix_syslog_dead_letters_organization_id"),
        "syslog_dead_letters",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_syslog_dead_letters_provider_id"), "syslog_dead_letters", ["provider_id"], unique=False
    )
    op.create_index(op.f("ix_syslog_dead_letters_reason"), "syslog_dead_letters", ["reason"], unique=False)
    op.create_index(
        op.f("ix_syslog_dead_letters_received_at"), "syslog_dead_letters", ["received_at"], unique=False
    )
    op.create_table(
        "mail_gateways",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("provider_type", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("vendor", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("settings", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(length=320), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_mail_gateways_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_gateways")),
        sa.UniqueConstraint("organization_id", "provider_id", name="uq_mail_gateway"),
    )
    op.create_index(op.f("ix_mail_gateways_created_at"), "mail_gateways", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_mail_gateways_organization_id"), "mail_gateways", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_mail_gateways_provider_id"), "mail_gateways", ["provider_id"], unique=False)
    op.create_table(
        "mail_routes",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("hop_sequence", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_mail_routes_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_routes")),
    )
    op.create_index(op.f("ix_mail_routes_created_at"), "mail_routes", ["created_at"], unique=False)
    op.create_index(op.f("ix_mail_routes_organization_id"), "mail_routes", ["organization_id"], unique=False)
    op.create_table(
        "pilot_metric_snapshots",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metrics", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_pilot_metric_snapshots_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pilot_metric_snapshots")),
        sa.UniqueConstraint("organization_id", "period_start", name="uq_pilot_metric_period"),
    )
    op.create_index(
        op.f("ix_pilot_metric_snapshots_created_at"), "pilot_metric_snapshots", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_pilot_metric_snapshots_organization_id"),
        "pilot_metric_snapshots",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pilot_metric_snapshots_period_start"),
        "pilot_metric_snapshots",
        ["period_start"],
        unique=False,
    )
    op.create_table(
        "rule_statistics",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("rule_id", sa.String(length=32), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("trigger_count", sa.Integer(), nullable=False),
        sa.Column("confirmed_tp", sa.Integer(), nullable=False),
        sa.Column("confirmed_fp", sa.Integer(), nullable=False),
        sa.Column("suppressed_count", sa.Integer(), nullable=False),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_rule_statistics_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_statistics")),
        sa.UniqueConstraint("organization_id", "rule_id", name="uq_rule_statistic"),
    )
    op.create_index(op.f("ix_rule_statistics_created_at"), "rule_statistics", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_rule_statistics_last_triggered_at"), "rule_statistics", ["last_triggered_at"], unique=False
    )
    op.create_index(
        op.f("ix_rule_statistics_organization_id"), "rule_statistics", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_rule_statistics_rule_id"), "rule_statistics", ["rule_id"], unique=False)
    op.create_table(
        "gateway_capability_states",
        sa.Column("gateway_id", sa.String(length=32), nullable=False),
        sa.Column("capability", sa.String(length=32), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.String(length=500), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["gateway_id"],
            ["mail_gateways.id"],
            name=op.f("fk_gateway_capability_states_gateway_id_mail_gateways"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gateway_capability_states")),
        sa.UniqueConstraint("gateway_id", "capability", name="uq_gateway_capability"),
    )
    op.create_index(
        op.f("ix_gateway_capability_states_capability"),
        "gateway_capability_states",
        ["capability"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_capability_states_created_at"),
        "gateway_capability_states",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_capability_states_gateway_id"),
        "gateway_capability_states",
        ["gateway_id"],
        unique=False,
    )
    op.create_table(
        "gateway_credentials",
        sa.Column("gateway_id", sa.String(length=32), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("auth_scheme", sa.String(length=32), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("secret_ref", sa.String(length=255), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_by", sa.String(length=320), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["gateway_id"],
            ["mail_gateways.id"],
            name=op.f("fk_gateway_credentials_gateway_id_mail_gateways"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gateway_credentials")),
        sa.UniqueConstraint("gateway_id", "purpose", name="uq_gateway_credential"),
    )
    op.create_index(
        op.f("ix_gateway_credentials_created_at"), "gateway_credentials", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_gateway_credentials_gateway_id"), "gateway_credentials", ["gateway_id"], unique=False
    )
    op.create_table(
        "gateway_evidence",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("provider_type", sa.String(length=32), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("threat_name", sa.String(length=255), nullable=False),
        sa.Column("engine", sa.String(length=128), nullable=False),
        sa.Column("policy", sa.String(length=255), nullable=False),
        sa.Column("evidence_source", sa.String(length=16), nullable=False),
        sa.Column("trusted", sa.Boolean(), nullable=False),
        sa.Column("trust_state", sa.String(length=32), nullable=False),
        sa.Column("trust_reason", sa.String(length=500), nullable=False),
        sa.Column("raw_reference", sa.String(length=255), nullable=False),
        sa.Column(
            "normalized_detail", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_gateway_evidence_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_gateway_evidence_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gateway_evidence")),
    )
    op.create_index(
        "ix_gateway_evidence_message", "gateway_evidence", ["message_id", "provider_id"], unique=False
    )
    op.create_index(op.f("ix_gateway_evidence_message_id"), "gateway_evidence", ["message_id"], unique=False)
    op.create_index(
        op.f("ix_gateway_evidence_observed_at"), "gateway_evidence", ["observed_at"], unique=False
    )
    op.create_index(
        op.f("ix_gateway_evidence_organization_id"), "gateway_evidence", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_gateway_evidence_provider_id"), "gateway_evidence", ["provider_id"], unique=False
    )
    op.create_index(
        "ix_gateway_evidence_time", "gateway_evidence", ["organization_id", "observed_at"], unique=False
    )
    op.create_index(op.f("ix_gateway_evidence_trusted"), "gateway_evidence", ["trusted"], unique=False)
    op.create_index(op.f("ix_gateway_evidence_verdict"), "gateway_evidence", ["verdict"], unique=False)
    op.create_table(
        "mail_gateway_nodes",
        sa.Column("gateway_id", sa.String(length=32), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("ip_networks", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["gateway_id"],
            ["mail_gateways.id"],
            name=op.f("fk_mail_gateway_nodes_gateway_id_mail_gateways"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_gateway_nodes")),
    )
    op.create_index(
        op.f("ix_mail_gateway_nodes_created_at"), "mail_gateway_nodes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_mail_gateway_nodes_gateway_id"), "mail_gateway_nodes", ["gateway_id"], unique=False
    )
    op.create_index(op.f("ix_mail_gateway_nodes_hostname"), "mail_gateway_nodes", ["hostname"], unique=False)
    op.create_table(
        "message_traces",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("internet_message_id", sa.String(length=998), nullable=False),
        sa.Column("queue_id", sa.String(length=64), nullable=False),
        sa.Column("sender", sa.String(length=320), nullable=False),
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("subject_hash", sa.String(length=64), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("events", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("final_action", sa.String(length=32), nullable=False),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_message_traces_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_message_traces_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_traces")),
    )
    op.create_index(
        op.f("ix_message_traces_content_sha256"), "message_traces", ["content_sha256"], unique=False
    )
    op.create_index(
        "ix_message_traces_correlation",
        "message_traces",
        ["organization_id", "internet_message_id"],
        unique=False,
    )
    op.create_index(op.f("ix_message_traces_created_at"), "message_traces", ["created_at"], unique=False)
    op.create_index(op.f("ix_message_traces_message_id"), "message_traces", ["message_id"], unique=False)
    op.create_index(
        op.f("ix_message_traces_organization_id"), "message_traces", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_message_traces_provider_id"), "message_traces", ["provider_id"], unique=False)
    op.create_index(
        "ix_message_traces_queue", "message_traces", ["organization_id", "queue_id"], unique=False
    )
    op.create_index(op.f("ix_message_traces_subject_hash"), "message_traces", ["subject_hash"], unique=False)
    op.create_table(
        "trusted_mail_hops",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("gateway_id", sa.String(length=32), nullable=True),
        sa.Column("hop_type", sa.String(length=32), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("ip_networks", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column(
            "expected_headers", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("authserv_ids", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("position_in_chain", sa.Integer(), nullable=True),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.String(length=320), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["gateway_id"],
            ["mail_gateways.id"],
            name=op.f("fk_trusted_mail_hops_gateway_id_mail_gateways"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_trusted_mail_hops_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trusted_mail_hops")),
    )
    op.create_index("ix_trusted_hops_org", "trusted_mail_hops", ["organization_id", "enabled"], unique=False)
    op.create_index(
        op.f("ix_trusted_mail_hops_created_at"), "trusted_mail_hops", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_trusted_mail_hops_gateway_id"), "trusted_mail_hops", ["gateway_id"], unique=False
    )
    op.create_index(op.f("ix_trusted_mail_hops_hostname"), "trusted_mail_hops", ["hostname"], unique=False)
    op.create_index(
        op.f("ix_trusted_mail_hops_organization_id"), "trusted_mail_hops", ["organization_id"], unique=False
    )
    op.create_table(
        "gateway_conflicts",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column("incident_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("providers", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("detail", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=320), nullable=True),
        sa.Column("resolution", sa.String(length=500), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_gateway_conflicts_incident_id_incidents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_gateway_conflicts_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_gateway_conflicts_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gateway_conflicts")),
    )
    op.create_index(
        op.f("ix_gateway_conflicts_detected_at"), "gateway_conflicts", ["detected_at"], unique=False
    )
    op.create_index(
        op.f("ix_gateway_conflicts_incident_id"), "gateway_conflicts", ["incident_id"], unique=False
    )
    op.create_index(op.f("ix_gateway_conflicts_kind"), "gateway_conflicts", ["kind"], unique=False)
    op.create_index(
        op.f("ix_gateway_conflicts_message_id"), "gateway_conflicts", ["message_id"], unique=False
    )
    op.create_index(
        "ix_gateway_conflicts_open", "gateway_conflicts", ["organization_id", "resolved_at"], unique=False
    )
    op.create_index(
        op.f("ix_gateway_conflicts_organization_id"), "gateway_conflicts", ["organization_id"], unique=False
    )
    op.create_table(
        "intake_records",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "addin",
                "addin_report",
                "security_mailbox",
                "shadow",
                "upload",
                "api",
                name="intake_source_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=320), nullable=False),
        sa.Column("mailbox_uid", sa.String(length=128), nullable=False),
        sa.Column("internet_message_id", sa.String(length=998), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("reported_by", sa.String(length=320), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "FETCHED",
                "STORED",
                "JOB_CREATED",
                "ACKNOWLEDGED",
                "DUPLICATE",
                "RETRY",
                "DEAD_LETTER",
                name="intake_state_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("raw_storage_key", sa.String(length=512), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("oversized", sa.Boolean(), nullable=False),
        sa.Column("analysis_job_id", sa.String(length=32), nullable=True),
        sa.Column("duplicate_of_id", sa.String(length=32), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("warnings", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_intake_records_analysis_job_id_analysis_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_intake_records_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intake_records")),
        sa.UniqueConstraint("organization_id", "source_id", "mailbox_uid", name="uq_intake_uid"),
    )
    op.create_index(
        "ix_intake_content", "intake_records", ["organization_id", "content_sha256"], unique=False
    )
    op.create_index(
        op.f("ix_intake_records_analysis_job_id"), "intake_records", ["analysis_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_intake_records_content_sha256"), "intake_records", ["content_sha256"], unique=False
    )
    op.create_index(op.f("ix_intake_records_created_at"), "intake_records", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_intake_records_duplicate_of_id"), "intake_records", ["duplicate_of_id"], unique=False
    )
    op.create_index(op.f("ix_intake_records_fetched_at"), "intake_records", ["fetched_at"], unique=False)
    op.create_index(
        op.f("ix_intake_records_internet_message_id"), "intake_records", ["internet_message_id"], unique=False
    )
    op.create_index(op.f("ix_intake_records_mailbox_uid"), "intake_records", ["mailbox_uid"], unique=False)
    op.create_index(
        op.f("ix_intake_records_organization_id"), "intake_records", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_intake_records_state"), "intake_records", ["state"], unique=False)
    op.create_index("ix_intake_state", "intake_records", ["organization_id", "state"], unique=False)
    # Existing deployments already hold rows in these tables, so a NOT NULL column needs a
    # value for them. The server default fills the backlog and is then dropped: the default
    # belongs in the model, and leaving it in the schema would let an INSERT that forgot the
    # column succeed silently.
    op.add_column(
        "analysis_jobs",
        sa.Column(
            "scan_completeness",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'FULL'"),
        ),
    )
    op.alter_column("analysis_jobs", "scan_completeness", server_default=None)
    op.create_index(
        op.f("ix_analysis_jobs_scan_completeness"), "analysis_jobs", ["scan_completeness"], unique=False
    )
    op.add_column(
        "analysis_results",
        sa.Column(
            "scan_completeness",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'FULL'"),
        ),
    )
    op.alter_column("analysis_results", "scan_completeness", server_default=None)
    op.add_column(
        "protected_identities",
        sa.Column(
            "risk_class",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'STANDARD'"),
        ),
    )
    op.alter_column("protected_identities", "risk_class", server_default=None)
    op.add_column(
        "protected_identities",
        sa.Column(
            "vip",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.alter_column("protected_identities", "vip", server_default=None)
    op.add_column(
        "protected_identities",
        sa.Column(
            "protected",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )
    op.alter_column("protected_identities", "protected", server_default=None)
    op.add_column(
        "protected_identities",
        sa.Column(
            "source",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'MANUAL'"),
        ),
    )
    op.alter_column("protected_identities", "source", server_default=None)
    op.create_index(
        op.f("ix_protected_identities_risk_class"), "protected_identities", ["risk_class"], unique=False
    )
    op.create_index(op.f("ix_protected_identities_vip"), "protected_identities", ["vip"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_protected_identities_vip"), table_name="protected_identities")
    op.drop_index(op.f("ix_protected_identities_risk_class"), table_name="protected_identities")
    op.drop_column("protected_identities", "source")
    op.drop_column("protected_identities", "protected")
    op.drop_column("protected_identities", "vip")
    op.drop_column("protected_identities", "risk_class")
    op.drop_column("analysis_results", "scan_completeness")
    op.drop_index(op.f("ix_analysis_jobs_scan_completeness"), table_name="analysis_jobs")
    op.drop_column("analysis_jobs", "scan_completeness")
    op.drop_index("ix_intake_state", table_name="intake_records")
    op.drop_index(op.f("ix_intake_records_state"), table_name="intake_records")
    op.drop_index(op.f("ix_intake_records_organization_id"), table_name="intake_records")
    op.drop_index(op.f("ix_intake_records_mailbox_uid"), table_name="intake_records")
    op.drop_index(op.f("ix_intake_records_internet_message_id"), table_name="intake_records")
    op.drop_index(op.f("ix_intake_records_fetched_at"), table_name="intake_records")
    op.drop_index(op.f("ix_intake_records_duplicate_of_id"), table_name="intake_records")
    op.drop_index(op.f("ix_intake_records_created_at"), table_name="intake_records")
    op.drop_index(op.f("ix_intake_records_content_sha256"), table_name="intake_records")
    op.drop_index(op.f("ix_intake_records_analysis_job_id"), table_name="intake_records")
    op.drop_index("ix_intake_content", table_name="intake_records")
    op.drop_table("intake_records")
    op.drop_index(op.f("ix_gateway_conflicts_organization_id"), table_name="gateway_conflicts")
    op.drop_index("ix_gateway_conflicts_open", table_name="gateway_conflicts")
    op.drop_index(op.f("ix_gateway_conflicts_message_id"), table_name="gateway_conflicts")
    op.drop_index(op.f("ix_gateway_conflicts_kind"), table_name="gateway_conflicts")
    op.drop_index(op.f("ix_gateway_conflicts_incident_id"), table_name="gateway_conflicts")
    op.drop_index(op.f("ix_gateway_conflicts_detected_at"), table_name="gateway_conflicts")
    op.drop_table("gateway_conflicts")
    op.drop_index(op.f("ix_trusted_mail_hops_organization_id"), table_name="trusted_mail_hops")
    op.drop_index(op.f("ix_trusted_mail_hops_hostname"), table_name="trusted_mail_hops")
    op.drop_index(op.f("ix_trusted_mail_hops_gateway_id"), table_name="trusted_mail_hops")
    op.drop_index(op.f("ix_trusted_mail_hops_created_at"), table_name="trusted_mail_hops")
    op.drop_index("ix_trusted_hops_org", table_name="trusted_mail_hops")
    op.drop_table("trusted_mail_hops")
    op.drop_index(op.f("ix_message_traces_subject_hash"), table_name="message_traces")
    op.drop_index("ix_message_traces_queue", table_name="message_traces")
    op.drop_index(op.f("ix_message_traces_provider_id"), table_name="message_traces")
    op.drop_index(op.f("ix_message_traces_organization_id"), table_name="message_traces")
    op.drop_index(op.f("ix_message_traces_message_id"), table_name="message_traces")
    op.drop_index(op.f("ix_message_traces_created_at"), table_name="message_traces")
    op.drop_index("ix_message_traces_correlation", table_name="message_traces")
    op.drop_index(op.f("ix_message_traces_content_sha256"), table_name="message_traces")
    op.drop_table("message_traces")
    op.drop_index(op.f("ix_mail_gateway_nodes_hostname"), table_name="mail_gateway_nodes")
    op.drop_index(op.f("ix_mail_gateway_nodes_gateway_id"), table_name="mail_gateway_nodes")
    op.drop_index(op.f("ix_mail_gateway_nodes_created_at"), table_name="mail_gateway_nodes")
    op.drop_table("mail_gateway_nodes")
    op.drop_index(op.f("ix_gateway_evidence_verdict"), table_name="gateway_evidence")
    op.drop_index(op.f("ix_gateway_evidence_trusted"), table_name="gateway_evidence")
    op.drop_index("ix_gateway_evidence_time", table_name="gateway_evidence")
    op.drop_index(op.f("ix_gateway_evidence_provider_id"), table_name="gateway_evidence")
    op.drop_index(op.f("ix_gateway_evidence_organization_id"), table_name="gateway_evidence")
    op.drop_index(op.f("ix_gateway_evidence_observed_at"), table_name="gateway_evidence")
    op.drop_index(op.f("ix_gateway_evidence_message_id"), table_name="gateway_evidence")
    op.drop_index("ix_gateway_evidence_message", table_name="gateway_evidence")
    op.drop_table("gateway_evidence")
    op.drop_index(op.f("ix_gateway_credentials_gateway_id"), table_name="gateway_credentials")
    op.drop_index(op.f("ix_gateway_credentials_created_at"), table_name="gateway_credentials")
    op.drop_table("gateway_credentials")
    op.drop_index(op.f("ix_gateway_capability_states_gateway_id"), table_name="gateway_capability_states")
    op.drop_index(op.f("ix_gateway_capability_states_created_at"), table_name="gateway_capability_states")
    op.drop_index(op.f("ix_gateway_capability_states_capability"), table_name="gateway_capability_states")
    op.drop_table("gateway_capability_states")
    op.drop_index(op.f("ix_rule_statistics_rule_id"), table_name="rule_statistics")
    op.drop_index(op.f("ix_rule_statistics_organization_id"), table_name="rule_statistics")
    op.drop_index(op.f("ix_rule_statistics_last_triggered_at"), table_name="rule_statistics")
    op.drop_index(op.f("ix_rule_statistics_created_at"), table_name="rule_statistics")
    op.drop_table("rule_statistics")
    op.drop_index(op.f("ix_pilot_metric_snapshots_period_start"), table_name="pilot_metric_snapshots")
    op.drop_index(op.f("ix_pilot_metric_snapshots_organization_id"), table_name="pilot_metric_snapshots")
    op.drop_index(op.f("ix_pilot_metric_snapshots_created_at"), table_name="pilot_metric_snapshots")
    op.drop_table("pilot_metric_snapshots")
    op.drop_index(op.f("ix_mail_routes_organization_id"), table_name="mail_routes")
    op.drop_index(op.f("ix_mail_routes_created_at"), table_name="mail_routes")
    op.drop_table("mail_routes")
    op.drop_index(op.f("ix_mail_gateways_provider_id"), table_name="mail_gateways")
    op.drop_index(op.f("ix_mail_gateways_organization_id"), table_name="mail_gateways")
    op.drop_index(op.f("ix_mail_gateways_created_at"), table_name="mail_gateways")
    op.drop_table("mail_gateways")
    op.drop_index(op.f("ix_syslog_dead_letters_received_at"), table_name="syslog_dead_letters")
    op.drop_index(op.f("ix_syslog_dead_letters_reason"), table_name="syslog_dead_letters")
    op.drop_index(op.f("ix_syslog_dead_letters_provider_id"), table_name="syslog_dead_letters")
    op.drop_index(op.f("ix_syslog_dead_letters_organization_id"), table_name="syslog_dead_letters")
    op.drop_table("syslog_dead_letters")
    # ### end Alembic commands ###
