"""initial schema

Revision ID: 043db9650df6
Revises:
Create Date: 2026-09-28 04:09:56.870459
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - used by rendered JSONB variants
from sqlalchemy.dialects import postgresql

revision: str = "043db9650df6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("organization_id", sa.String(length=32), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=32), nullable=True),
        sa.Column("actor_email", sa.String(length=320), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index("ix_audit_actor", ["actor_email", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_object_id"), ["object_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_object_type"), ["object_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_events_request_id"), ["request_id"], unique=False)
        batch_op.create_index("ix_audit_org_time", ["organization_id", "created_at"], unique=False)

    op.create_table(
        "health_snapshots",
        sa.Column("component", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_snapshots")),
    )
    with op.batch_alter_table("health_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_health_snapshots_component"), ["component"], unique=False)
        batch_op.create_index(batch_op.f("ix_health_snapshots_created_at"), ["created_at"], unique=False)

    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "corporate_domains", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "trusted_infrastructure_domains",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("settings", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_organizations_created_at"), ["created_at"], unique=False)

    op.create_table(
        "retention_runs",
        sa.Column("organization_id", sa.String(length=32), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("deleted_count", sa.Integer(), nullable=False),
        sa.Column("cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detail", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retention_runs")),
    )
    with op.batch_alter_table("retention_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_retention_runs_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_retention_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_retention_runs_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "cases",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=320), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_cases_organization_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
    )
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cases_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_organization_id"), ["organization_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_status"), ["status"], unique=False)

    op.create_table(
        "directory_sync_runs",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("incremental", sa.Boolean(), nullable=False),
        sa.Column("created", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("disabled", sa.Integer(), nullable=False),
        sa.Column("errors", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("high_watermark", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_directory_sync_runs_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_directory_sync_runs")),
    )
    with op.batch_alter_table("directory_sync_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_directory_sync_runs_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "indicators",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column(
            "ioc_type",
            sa.Enum(
                "sha256",
                "domain",
                "url",
                "ipv4",
                "ipv6",
                "email",
                "cert_fingerprint",
                name="ioc_type_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=1024), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sighting_count", sa.Integer(), nullable=False),
        sa.Column(
            "worst_status",
            sa.Enum(
                "KNOWN_BAD",
                "SUSPICIOUS",
                "NO_NEGATIVE_REPUTATION",
                "UNKNOWN",
                "NOT_SUPPORTED",
                "RATE_LIMITED",
                "PROVIDER_UNAVAILABLE",
                "POLICY_BLOCKED",
                "ERROR",
                name="ti_status_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("confirmed_malicious", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_indicators_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indicators")),
        sa.UniqueConstraint("organization_id", "ioc_type", "value", name="uq_indicator_value"),
    )
    with op.batch_alter_table("indicators", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_indicators_confirmed_malicious"), ["confirmed_malicious"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_indicators_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_indicators_ioc_type"), ["ioc_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_indicators_last_seen"), ["last_seen"], unique=False)
        batch_op.create_index(batch_op.f("ix_indicators_organization_id"), ["organization_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_indicators_value"), ["value"], unique=False)
        batch_op.create_index(batch_op.f("ix_indicators_worst_status"), ["worst_status"], unique=False)

    op.create_table(
        "mail_messages",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("internet_message_id", sa.String(length=998), nullable=False),
        sa.Column("raw_sha256", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=1000), nullable=False),
        sa.Column("sender_address", sa.String(length=320), nullable=False),
        sa.Column("sender_display_name", sa.String(length=512), nullable=False),
        sa.Column("sender_domain", sa.String(length=255), nullable=False),
        sa.Column("reply_to_address", sa.String(length=320), nullable=False),
        sa.Column("return_path", sa.String(length=320), nullable=False),
        sa.Column("recipient_count", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "addin",
                "addin_report",
                "security_mailbox",
                "shadow",
                "upload",
                "api",
                name="intake_source_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_mailbox", sa.String(length=320), nullable=False),
        sa.Column("exchange_item_id", sa.String(length=512), nullable=False),
        sa.Column("has_attachments", sa.Boolean(), nullable=False),
        sa.Column("url_count", sa.Integer(), nullable=False),
        sa.Column("encrypted", sa.Boolean(), nullable=False),
        sa.Column("parse_errors", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("auth_summary", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("campaign_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "campaign_components", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("body_simhash", sa.String(length=32), nullable=False),
        sa.Column("reported_by", sa.String(length=320), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_mail_messages_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_messages")),
    )
    with op.batch_alter_table("mail_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mail_messages_campaign_fingerprint"), ["campaign_fingerprint"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_mail_messages_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            "ix_mail_messages_fingerprint", ["organization_id", "campaign_fingerprint"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_mail_messages_internet_message_id"), ["internet_message_id"], unique=False
        )
        batch_op.create_index(
            "ix_mail_messages_org_received", ["organization_id", "received_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_mail_messages_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_mail_messages_raw_sha256"), ["raw_sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_mail_messages_received_at"), ["received_at"], unique=False)
        batch_op.create_index("ix_mail_messages_sender", ["organization_id", "sender_address"], unique=False)
        batch_op.create_index(batch_op.f("ix_mail_messages_sender_address"), ["sender_address"], unique=False)
        batch_op.create_index(batch_op.f("ix_mail_messages_sender_domain"), ["sender_domain"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notifications_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_event"), ["event"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notifications_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_state"), ["state"], unique=False)

    op.create_table(
        "policies",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=320), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_policies_organization_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policies")),
        sa.UniqueConstraint("organization_id", "key", name="uq_policy_key"),
    )
    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_policies_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_policies_key"), ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_policies_organization_id"), ["organization_id"], unique=False)

    op.create_table(
        "provider_configs",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("settings", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("secret_ref", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=320), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_provider_configs_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_configs")),
        sa.UniqueConstraint("organization_id", "provider_id", name="uq_provider_config"),
    )
    with op.batch_alter_table("provider_configs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_provider_configs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_provider_configs_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_provider_configs_provider_id"), ["provider_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "employee",
                "security_viewer",
                "security_analyst",
                "security_admin",
                "platform_admin",
                name="role_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("auth_source", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_users_organization_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_organization_id"), ["organization_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)

    op.create_table(
        "analysis_jobs",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column("requested_by", sa.String(length=32), nullable=True),
        sa.Column("requester_mailbox", sa.String(length=320), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "addin",
                "addin_report",
                "security_mailbox",
                "shadow",
                "upload",
                "api",
                name="intake_source_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "QUEUED",
                "ANALYZING",
                "COMPLETED",
                "PARTIAL",
                "FAILED",
                name="job_state_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "ti_state",
            sa.Enum(
                "NOT_REQUIRED",
                "NOT_CONFIGURED",
                "PENDING",
                "COMPLETED",
                "PARTIAL",
                "UNAVAILABLE",
                name="ti_state_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_ANALYZED",
                "QUEUED",
                "ANALYZING",
                "LOW_RISK",
                "SUSPICIOUS",
                "HIGH_RISK",
                "MALICIOUS",
                "UNKNOWN",
                "PROVIDER_UNAVAILABLE",
                "ERROR",
                "REPORTED",
                "UNDER_INVESTIGATION",
                "CLOSED",
                name="analysis_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("is_report", sa.Boolean(), nullable=False),
        sa.Column("user_note", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("warnings", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_analysis_jobs_message_id_mail_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_analysis_jobs_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_analysis_jobs_requested_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_jobs")),
        sa.UniqueConstraint("idempotency_key", name="uq_jobs_idempotency"),
    )
    with op.batch_alter_table("analysis_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analysis_jobs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_analysis_jobs_message_id"), ["message_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_analysis_jobs_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analysis_jobs_requested_by"), ["requested_by"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_analysis_jobs_requester_mailbox"), ["requester_mailbox"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analysis_jobs_state"), ["state"], unique=False)
        batch_op.create_index(batch_op.f("ix_analysis_jobs_status"), ["status"], unique=False)
        batch_op.create_index("ix_jobs_org_state", ["organization_id", "state"], unique=False)

    op.create_table(
        "attachments",
        sa.Column("message_id", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("normalized_filename", sa.String(length=512), nullable=False),
        sa.Column("declared_mime", sa.String(length=255), nullable=False),
        sa.Column("detected_type", sa.String(length=64), nullable=False),
        sa.Column("extension", sa.String(length=32), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("sha1", sa.String(length=40), nullable=True),
        sa.Column("md5", sa.String(length=32), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("parent_sha256", sa.String(length=64), nullable=True),
        sa.Column("is_archive", sa.Boolean(), nullable=False),
        sa.Column("encrypted", sa.Boolean(), nullable=False),
        sa.Column("flags", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column(
            "archive_summary", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scan_result", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_attachments_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attachments_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_attachments_message_id"), ["message_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_attachments_sha256"), ["sha256"], unique=False)

    op.create_table(
        "detection_exceptions",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column(
            "exception_type",
            sa.Enum(
                "trusted_sender",
                "trusted_domain",
                "trusted_sender_domain_pair",
                "approved_delegated_service",
                "approved_marketing_platform",
                "temporary",
                "rule_suppression",
                name="exception_type_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("rule_id", sa.String(length=32), nullable=True),
        sa.Column("owner_id", sa.String(length=32), nullable=True),
        sa.Column("owner_email", sa.String(length=320), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(length=320), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_detection_exceptions_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_detection_exceptions_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection_exceptions")),
    )
    with op.batch_alter_table("detection_exceptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_detection_exceptions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_detection_exceptions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_detection_exceptions_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_detection_exceptions_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_detection_exceptions_value"), ["value"], unique=False)
        batch_op.create_index("ix_exceptions_org_active", ["organization_id", "revoked_at"], unique=False)

    op.create_table(
        "incidents",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("case_id", sa.String(length=32), nullable=True),
        sa.Column("number", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "TRIAGE",
                "INVESTIGATING",
                "CONFIRMED_PHISHING",
                "CONFIRMED_MALWARE",
                "CONFIRMED_BEC",
                "FALSE_POSITIVE",
                "BENIGN",
                "REMEDIATION_PENDING",
                "REMEDIATED",
                "CLOSED",
                name="incident_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("info", "low", "medium", "high", "critical", name="severity_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("assigned_to", sa.String(length=32), nullable=True),
        sa.Column("opened_by", sa.String(length=320), nullable=True),
        sa.Column("affected_users", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("timeline", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triaged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remediated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], name=op.f("fk_incidents_assigned_to_users")),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_incidents_case_id_cases"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_incidents_organization_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incidents_assigned_to"), ["assigned_to"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_number"), ["number"], unique=False)
        batch_op.create_index("ix_incidents_org_status", ["organization_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_organization_id"), ["organization_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_status"), ["status"], unique=False)

    op.create_table(
        "indicator_observations",
        sa.Column("indicator_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column("context", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["indicator_id"],
            ["indicators.id"],
            name=op.f("fk_indicator_observations_indicator_id_indicators"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_indicator_observations_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indicator_observations")),
    )
    with op.batch_alter_table("indicator_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_indicator_observations_indicator_id"), ["indicator_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_indicator_observations_message_id"), ["message_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_indicator_observations_observed_at"), ["observed_at"], unique=False
        )
        batch_op.create_index("ix_observations_indicator_time", ["indicator_id", "observed_at"], unique=False)

    op.create_table(
        "mail_contents",
        sa.Column("message_id", sa.String(length=32), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=True),
        sa.Column("sanitized_html", sa.Text(), nullable=True),
        sa.Column("raw_body_key", sa.String(length=512), nullable=True),
        sa.Column("raw_eml_key", sa.String(length=512), nullable=True),
        sa.Column("normalized_purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_body_purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_eml_purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_mail_contents_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_contents")),
    )
    with op.batch_alter_table("mail_contents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mail_contents_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mail_contents_message_id"), ["message_id"], unique=True)

    op.create_table(
        "mail_headers",
        sa.Column("message_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_mail_headers_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_headers")),
    )
    with op.batch_alter_table("mail_headers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mail_headers_message_id"), ["message_id"], unique=False)

    op.create_table(
        "mail_recipients",
        sa.Column("message_id", sa.String(length=32), nullable=False),
        sa.Column("address", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_mail_recipients_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_recipients")),
    )
    with op.batch_alter_table("mail_recipients", schema=None) as batch_op:
        batch_op.create_index("ix_mail_recipients_address", ["address"], unique=False)
        batch_op.create_index(batch_op.f("ix_mail_recipients_message_id"), ["message_id"], unique=False)

    op.create_table(
        "mailbox_identities",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("address", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("aliases", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("department", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("directory_object_id", sa.String(length=128), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("deleted_in_directory", sa.Boolean(), nullable=False),
        sa.Column("manual_override", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_mailbox_identities_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_mailbox_identities_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mailbox_identities")),
        sa.UniqueConstraint("organization_id", "address", name="uq_mailbox_address"),
    )
    with op.batch_alter_table("mailbox_identities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mailbox_identities_address"), ["address"], unique=False)
        batch_op.create_index(batch_op.f("ix_mailbox_identities_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_mailbox_identities_directory_object_id"), ["directory_object_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_mailbox_identities_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_mailbox_identities_user_id"), ["user_id"], unique=False)

    op.create_table(
        "policy_versions",
        sa.Column("policy_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("value", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("changed_by", sa.String(length=320), nullable=True),
        sa.Column("change_reason", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
            name=op.f("fk_policy_versions_policy_id_policies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_versions")),
    )
    with op.batch_alter_table("policy_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_policy_versions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_policy_versions_policy_id"), ["policy_id"], unique=False)

    op.create_table(
        "risk_verdicts",
        sa.Column("message_id", sa.String(length=32), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "LOW_RISK",
                "SUSPICIOUS",
                "HIGH_RISK",
                "MALICIOUS",
                "UNKNOWN",
                name="risk_level_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("changed_by", sa.String(length=320), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_risk_verdicts_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_verdicts")),
    )
    with op.batch_alter_table("risk_verdicts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_risk_verdicts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_risk_verdicts_message_id"), ["message_id"], unique=False)

    op.create_table(
        "analysis_results",
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column(
            "classification",
            sa.Enum(
                "LOW_RISK",
                "SUSPICIOUS",
                "HIGH_RISK",
                "MALICIOUS",
                "UNKNOWN",
                name="risk_level_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("confidence_value", sa.Float(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("reasons", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("hard_signals", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column(
            "suppressed_signals", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("sources", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column(
            "missing_evidence", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("facts", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column("ruleset_fingerprint", sa.Text(), nullable=False),
        sa.Column("risk_engine_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_analysis_results_job_id_analysis_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_analysis_results_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_results")),
    )
    with op.batch_alter_table("analysis_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_results_classification"), ["classification"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analysis_results_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_analysis_results_job_id"), ["job_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_analysis_results_message_id"), ["message_id"], unique=False)

    op.create_table(
        "analyst_notes",
        sa.Column("incident_id", sa.String(length=32), nullable=False),
        sa.Column("author_id", sa.String(length=32), nullable=True),
        sa.Column("author_email", sa.String(length=320), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_analyst_notes_author_id_users")),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_analyst_notes_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyst_notes")),
    )
    with op.batch_alter_table("analyst_notes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analyst_notes_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_analyst_notes_incident_id"), ["incident_id"], unique=False)

    op.create_table(
        "campaigns",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("recipient_count", sa.Integer(), nullable=False),
        sa.Column("reported_count", sa.Integer(), nullable=False),
        sa.Column(
            "verdict_distribution", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("indicators", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("subjects", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("senders", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("confirmed_malicious", sa.Boolean(), nullable=False),
        sa.Column("remediation_state", sa.String(length=32), nullable=False),
        sa.Column("incident_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_campaigns_incident_id_incidents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_campaigns_organization_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("organization_id", "fingerprint", name="uq_campaign_fingerprint"),
    )
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campaigns_confirmed_malicious"), ["confirmed_malicious"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_campaigns_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaigns_fingerprint"), ["fingerprint"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaigns_first_seen"), ["first_seen"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaigns_incident_id"), ["incident_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaigns_last_seen"), ["last_seen"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaigns_organization_id"), ["organization_id"], unique=False)

    op.create_table(
        "incident_indicators",
        sa.Column("incident_id", sa.String(length=32), nullable=False),
        sa.Column("indicator_id", sa.String(length=32), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_indicators_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["indicator_id"],
            ["indicators.id"],
            name=op.f("fk_incident_indicators_indicator_id_indicators"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_indicators")),
        sa.UniqueConstraint("incident_id", "indicator_id", name="uq_incident_indicator"),
    )
    with op.batch_alter_table("incident_indicators", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incident_indicators_incident_id"), ["incident_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_incident_indicators_indicator_id"), ["indicator_id"], unique=False
        )

    op.create_table(
        "incident_messages",
        sa.Column("incident_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_messages_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_incident_messages_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_messages")),
        sa.UniqueConstraint("incident_id", "message_id", name="uq_incident_message"),
    )
    with op.batch_alter_table("incident_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incident_messages_incident_id"), ["incident_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_incident_messages_message_id"), ["message_id"], unique=False)

    op.create_table(
        "protected_identities",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("mailbox_identity_id", sa.String(length=32), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("categories", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("aliases", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("name_variants", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column(
            "approved_delegates", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "approved_external_systems",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("department", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=320), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mailbox_identity_id"],
            ["mailbox_identities.id"],
            name=op.f("fk_protected_identities_mailbox_identity_id_mailbox_identities"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_protected_identities_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_protected_identities")),
    )
    with op.batch_alter_table("protected_identities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_protected_identities_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_protected_identities_email"), ["email"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_protected_identities_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "provider_lookups",
        sa.Column("analysis_job_id", sa.String(length=32), nullable=True),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column(
            "ioc_type",
            sa.Enum(
                "sha256",
                "domain",
                "url",
                "ipv4",
                "ipv6",
                "email",
                "cert_fingerprint",
                name="ioc_type_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("indicator_value", sa.String(length=1024), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "KNOWN_BAD",
                "SUSPICIOUS",
                "NO_NEGATIVE_REPUTATION",
                "UNKNOWN",
                "NOT_SUPPORTED",
                "RATE_LIMITED",
                "PROVIDER_UNAVAILABLE",
                "POLICY_BLOCKED",
                "ERROR",
                name="ti_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("malicious_count", sa.Integer(), nullable=True),
        sa.Column("total_count", sa.Integer(), nullable=True),
        sa.Column("categories", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("summary", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("from_cache", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(length=255), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_provider_lookups_analysis_job_id_analysis_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_lookups")),
    )
    with op.batch_alter_table("provider_lookups", schema=None) as batch_op:
        batch_op.create_index(
            "ix_lookups_provider_indicator", ["provider_id", "indicator_value"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_provider_lookups_analysis_job_id"), ["analysis_job_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_provider_lookups_fetched_at"), ["fetched_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_provider_lookups_provider_id"), ["provider_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_provider_lookups_status"), ["status"], unique=False)

    op.create_table(
        "campaign_messages",
        sa.Column("campaign_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_messages_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["mail_messages.id"],
            name=op.f("fk_campaign_messages_message_id_mail_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_messages")),
        sa.UniqueConstraint("campaign_id", "message_id", name="uq_campaign_message"),
    )
    with op.batch_alter_table("campaign_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_campaign_messages_campaign_id"), ["campaign_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaign_messages_message_id"), ["message_id"], unique=False)

    op.create_table(
        "detection_signals",
        sa.Column("result_id", sa.String(length=32), nullable=False),
        sa.Column("signal_id", sa.String(length=64), nullable=False),
        sa.Column("rule_id", sa.String(length=32), nullable=True),
        sa.Column("rule_version", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("info", "low", "medium", "high", "critical", name="severity_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("evidence", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("hard", sa.Boolean(), nullable=False),
        sa.Column("internal", sa.Boolean(), nullable=False),
        sa.Column("suppressed", sa.Boolean(), nullable=False),
        sa.Column("suppressed_by", sa.String(length=128), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["analysis_results.id"],
            name=op.f("fk_detection_signals_result_id_analysis_results"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection_signals")),
    )
    with op.batch_alter_table("detection_signals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_detection_signals_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_detection_signals_result_id"), ["result_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_detection_signals_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_detection_signals_severity"), ["severity"], unique=False)
        batch_op.create_index(batch_op.f("ix_detection_signals_signal_id"), ["signal_id"], unique=False)
        batch_op.create_index("ix_signals_rule", ["rule_id", "rule_version"], unique=False)

    op.create_table(
        "remediation_actions",
        sa.Column("organization_id", sa.String(length=32), nullable=False),
        sa.Column("incident_id", sa.String(length=32), nullable=True),
        sa.Column("campaign_id", sa.String(length=32), nullable=True),
        sa.Column(
            "action_type",
            sa.Enum(
                "locate",
                "quarantine",
                "delete",
                "block_sender",
                "block_domain",
                "transport_rule_proposal",
                "release",
                name="remediation_type_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "PROPOSED",
                "APPROVED",
                "REJECTED",
                "EXECUTED",
                "DRY_RUN_EXECUTED",
                "FAILED",
                "CANCELLED",
                name="remediation_state_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("proposed_by", sa.String(length=320), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "target_selector", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("affected_message_count", sa.Integer(), nullable=False),
        sa.Column(
            "affected_mailboxes", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("dry_run_report", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("required_approvals", sa.Integer(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_by", sa.String(length=320), nullable=True),
        sa.Column("rollback_token", sa.String(length=128), nullable=True),
        sa.Column("rollback_supported", sa.Boolean(), nullable=False),
        sa.Column("result", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "affected_message_count >= 0", name=op.f("ck_remediation_actions_affected_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_remediation_actions_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_remediation_actions_incident_id_incidents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_remediation_actions_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_remediation_actions")),
        sa.UniqueConstraint("idempotency_key", name="uq_remediation_idempotency"),
    )
    with op.batch_alter_table("remediation_actions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_remediation_actions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_remediation_actions_incident_id"), ["incident_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_remediation_actions_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_remediation_actions_state"), ["state"], unique=False)

    op.create_table(
        "approvals",
        sa.Column("action_id", sa.String(length=32), nullable=False),
        sa.Column("approver_id", sa.String(length=32), nullable=False),
        sa.Column("approver_email", sa.String(length=320), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("comment", sa.String(length=1000), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["remediation_actions.id"],
            name=op.f("fk_approvals_action_id_remediation_actions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["approver_id"], ["users.id"], name=op.f("fk_approvals_approver_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint("action_id", "approver_id", name="uq_approval_once"),
    )
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approvals_action_id"), ["action_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_approvals_approver_id"), ["approver_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approvals_approver_id"))
        batch_op.drop_index(batch_op.f("ix_approvals_action_id"))

    op.drop_table("approvals")
    with op.batch_alter_table("remediation_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_remediation_actions_state"))
        batch_op.drop_index(batch_op.f("ix_remediation_actions_organization_id"))
        batch_op.drop_index(batch_op.f("ix_remediation_actions_incident_id"))
        batch_op.drop_index(batch_op.f("ix_remediation_actions_created_at"))

    op.drop_table("remediation_actions")
    with op.batch_alter_table("detection_signals", schema=None) as batch_op:
        batch_op.drop_index("ix_signals_rule")
        batch_op.drop_index(batch_op.f("ix_detection_signals_signal_id"))
        batch_op.drop_index(batch_op.f("ix_detection_signals_severity"))
        batch_op.drop_index(batch_op.f("ix_detection_signals_rule_id"))
        batch_op.drop_index(batch_op.f("ix_detection_signals_result_id"))
        batch_op.drop_index(batch_op.f("ix_detection_signals_category"))

    op.drop_table("detection_signals")
    with op.batch_alter_table("campaign_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_messages_message_id"))
        batch_op.drop_index(batch_op.f("ix_campaign_messages_campaign_id"))

    op.drop_table("campaign_messages")
    with op.batch_alter_table("provider_lookups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_lookups_status"))
        batch_op.drop_index(batch_op.f("ix_provider_lookups_provider_id"))
        batch_op.drop_index(batch_op.f("ix_provider_lookups_fetched_at"))
        batch_op.drop_index(batch_op.f("ix_provider_lookups_analysis_job_id"))
        batch_op.drop_index("ix_lookups_provider_indicator")

    op.drop_table("provider_lookups")
    with op.batch_alter_table("protected_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_protected_identities_organization_id"))
        batch_op.drop_index(batch_op.f("ix_protected_identities_email"))
        batch_op.drop_index(batch_op.f("ix_protected_identities_created_at"))

    op.drop_table("protected_identities")
    with op.batch_alter_table("incident_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incident_messages_message_id"))
        batch_op.drop_index(batch_op.f("ix_incident_messages_incident_id"))

    op.drop_table("incident_messages")
    with op.batch_alter_table("incident_indicators", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incident_indicators_indicator_id"))
        batch_op.drop_index(batch_op.f("ix_incident_indicators_incident_id"))

    op.drop_table("incident_indicators")
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaigns_organization_id"))
        batch_op.drop_index(batch_op.f("ix_campaigns_last_seen"))
        batch_op.drop_index(batch_op.f("ix_campaigns_incident_id"))
        batch_op.drop_index(batch_op.f("ix_campaigns_first_seen"))
        batch_op.drop_index(batch_op.f("ix_campaigns_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_campaigns_created_at"))
        batch_op.drop_index(batch_op.f("ix_campaigns_confirmed_malicious"))

    op.drop_table("campaigns")
    with op.batch_alter_table("analyst_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analyst_notes_incident_id"))
        batch_op.drop_index(batch_op.f("ix_analyst_notes_created_at"))

    op.drop_table("analyst_notes")
    with op.batch_alter_table("analysis_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_results_message_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_results_job_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_results_created_at"))
        batch_op.drop_index(batch_op.f("ix_analysis_results_classification"))

    op.drop_table("analysis_results")
    with op.batch_alter_table("risk_verdicts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_verdicts_message_id"))
        batch_op.drop_index(batch_op.f("ix_risk_verdicts_created_at"))

    op.drop_table("risk_verdicts")
    with op.batch_alter_table("policy_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_policy_versions_policy_id"))
        batch_op.drop_index(batch_op.f("ix_policy_versions_created_at"))

    op.drop_table("policy_versions")
    with op.batch_alter_table("mailbox_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mailbox_identities_user_id"))
        batch_op.drop_index(batch_op.f("ix_mailbox_identities_organization_id"))
        batch_op.drop_index(batch_op.f("ix_mailbox_identities_directory_object_id"))
        batch_op.drop_index(batch_op.f("ix_mailbox_identities_created_at"))
        batch_op.drop_index(batch_op.f("ix_mailbox_identities_address"))

    op.drop_table("mailbox_identities")
    with op.batch_alter_table("mail_recipients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mail_recipients_message_id"))
        batch_op.drop_index("ix_mail_recipients_address")

    op.drop_table("mail_recipients")
    with op.batch_alter_table("mail_headers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mail_headers_message_id"))

    op.drop_table("mail_headers")
    with op.batch_alter_table("mail_contents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mail_contents_message_id"))
        batch_op.drop_index(batch_op.f("ix_mail_contents_created_at"))

    op.drop_table("mail_contents")
    with op.batch_alter_table("indicator_observations", schema=None) as batch_op:
        batch_op.drop_index("ix_observations_indicator_time")
        batch_op.drop_index(batch_op.f("ix_indicator_observations_observed_at"))
        batch_op.drop_index(batch_op.f("ix_indicator_observations_message_id"))
        batch_op.drop_index(batch_op.f("ix_indicator_observations_indicator_id"))

    op.drop_table("indicator_observations")
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incidents_status"))
        batch_op.drop_index(batch_op.f("ix_incidents_organization_id"))
        batch_op.drop_index("ix_incidents_org_status")
        batch_op.drop_index(batch_op.f("ix_incidents_number"))
        batch_op.drop_index(batch_op.f("ix_incidents_created_at"))
        batch_op.drop_index(batch_op.f("ix_incidents_assigned_to"))

    op.drop_table("incidents")
    with op.batch_alter_table("detection_exceptions", schema=None) as batch_op:
        batch_op.drop_index("ix_exceptions_org_active")
        batch_op.drop_index(batch_op.f("ix_detection_exceptions_value"))
        batch_op.drop_index(batch_op.f("ix_detection_exceptions_rule_id"))
        batch_op.drop_index(batch_op.f("ix_detection_exceptions_organization_id"))
        batch_op.drop_index(batch_op.f("ix_detection_exceptions_expires_at"))
        batch_op.drop_index(batch_op.f("ix_detection_exceptions_created_at"))

    op.drop_table("detection_exceptions")
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attachments_sha256"))
        batch_op.drop_index(batch_op.f("ix_attachments_message_id"))
        batch_op.drop_index(batch_op.f("ix_attachments_created_at"))

    op.drop_table("attachments")
    with op.batch_alter_table("analysis_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_org_state")
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_state"))
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_requester_mailbox"))
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_requested_by"))
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_organization_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_message_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_created_at"))

    op.drop_table("analysis_jobs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_organization_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_created_at"))

    op.drop_table("users")
    with op.batch_alter_table("provider_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_configs_provider_id"))
        batch_op.drop_index(batch_op.f("ix_provider_configs_organization_id"))
        batch_op.drop_index(batch_op.f("ix_provider_configs_created_at"))

    op.drop_table("provider_configs")
    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_policies_organization_id"))
        batch_op.drop_index(batch_op.f("ix_policies_key"))
        batch_op.drop_index(batch_op.f("ix_policies_created_at"))

    op.drop_table("policies")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_state"))
        batch_op.drop_index(batch_op.f("ix_notifications_organization_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_event"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("mail_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mail_messages_sender_domain"))
        batch_op.drop_index(batch_op.f("ix_mail_messages_sender_address"))
        batch_op.drop_index("ix_mail_messages_sender")
        batch_op.drop_index(batch_op.f("ix_mail_messages_received_at"))
        batch_op.drop_index(batch_op.f("ix_mail_messages_raw_sha256"))
        batch_op.drop_index(batch_op.f("ix_mail_messages_organization_id"))
        batch_op.drop_index("ix_mail_messages_org_received")
        batch_op.drop_index(batch_op.f("ix_mail_messages_internet_message_id"))
        batch_op.drop_index("ix_mail_messages_fingerprint")
        batch_op.drop_index(batch_op.f("ix_mail_messages_created_at"))
        batch_op.drop_index(batch_op.f("ix_mail_messages_campaign_fingerprint"))

    op.drop_table("mail_messages")
    with op.batch_alter_table("indicators", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_indicators_worst_status"))
        batch_op.drop_index(batch_op.f("ix_indicators_value"))
        batch_op.drop_index(batch_op.f("ix_indicators_organization_id"))
        batch_op.drop_index(batch_op.f("ix_indicators_last_seen"))
        batch_op.drop_index(batch_op.f("ix_indicators_ioc_type"))
        batch_op.drop_index(batch_op.f("ix_indicators_created_at"))
        batch_op.drop_index(batch_op.f("ix_indicators_confirmed_malicious"))

    op.drop_table("indicators")
    with op.batch_alter_table("directory_sync_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_directory_sync_runs_organization_id"))

    op.drop_table("directory_sync_runs")
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cases_status"))
        batch_op.drop_index(batch_op.f("ix_cases_organization_id"))
        batch_op.drop_index(batch_op.f("ix_cases_created_at"))

    op.drop_table("cases")
    with op.batch_alter_table("retention_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_retention_runs_organization_id"))
        batch_op.drop_index(batch_op.f("ix_retention_runs_created_at"))
        batch_op.drop_index(batch_op.f("ix_retention_runs_category"))

    op.drop_table("retention_runs")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_created_at"))

    op.drop_table("organizations")
    with op.batch_alter_table("health_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_health_snapshots_created_at"))
        batch_op.drop_index(batch_op.f("ix_health_snapshots_component"))

    op.drop_table("health_snapshots")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_org_time")
        batch_op.drop_index(batch_op.f("ix_audit_events_request_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_organization_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_object_type"))
        batch_op.drop_index(batch_op.f("ix_audit_events_object_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))
        batch_op.drop_index("ix_audit_actor")

    op.drop_table("audit_events")
    # ### end Alembic commands ###
